//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectokevin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.reserva = new HashSet<reserva>();
        }
    
        public int id { get; set; }
        public string cli_codigo { get; set; }
        public string cli_descripcion { get; set; }
        public string cli_nombres { get; set; }
        public string cli_apellidos { get; set; }
        public string cli_telefono { get; set; }
        public string cli_email { get; set; }
        public string cli_direccion { get; set; }
        public int tic_id { get; set; }
    
        public virtual tipo_cliente tipo_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva> reserva { get; set; }
    }
}
