//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectokevin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comprobante()
        {
            this.comprobante_detalle = new HashSet<comprobante_detalle>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> com_fecha_registro { get; set; }
        public Nullable<decimal> com_importe { get; set; }
        public Nullable<decimal> com_igv { get; set; }
        public Nullable<int> com_estado { get; set; }
        public string com_nombre { get; set; }
        public string com_apellido { get; set; }
        public int res_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comprobante_detalle> comprobante_detalle { get; set; }
        public virtual reserva reserva { get; set; }
    }
}
