//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectokevin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comprobante_detalle
    {
        public int id { get; set; }
        public Nullable<decimal> hab_precio { get; set; }
        public Nullable<int> hab_cantidad { get; set; }
        public Nullable<decimal> hab_importe { get; set; }
        public int com_id { get; set; }
    
        public virtual comprobante comprobante { get; set; }
    }
}
