//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectokevin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserva()
        {
            this.comprobante = new HashSet<comprobante>();
        }
    
        public int id { get; set; }
        public int hab_id { get; set; }
        public int cli_id { get; set; }
        public int usu_id { get; set; }
        public Nullable<System.DateTime> res_fecha_registro { get; set; }
        public Nullable<System.DateTime> res_fecha_reserva { get; set; }
        public Nullable<int> res_estado { get; set; }
        public Nullable<decimal> res_monto { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comprobante> comprobante { get; set; }
        public virtual habitacion habitacion { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
